import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { initOfflineSync } from "@/lib/offlineQueue";
import { bootApplyUIPrefs } from "@/lib/uiScale";

bootApplyUIPrefs();

// Guard: never register a service worker inside Lovable preview/iframe contexts
const isInIframe = (() => {
  try {
    return window.self !== window.top;
  } catch {
    return true;
  }
})();
const host = window.location.hostname;
const isPreviewHost =
  host.includes("id-preview--") ||
  host.includes("lovableproject.com") ||
  host.includes("lovable.app") && host.includes("id-preview");

if (isPreviewHost || isInIframe) {
  // Cleanup any previously registered SW so preview never serves stale content
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.getRegistrations().then((rs) => rs.forEach((r) => r.unregister()));
  }
} else if ("serviceWorker" in navigator) {
  // Production / installed PWA: register the worker generated by vite-plugin-pwa
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      const updateSW = registerSW({
        immediate: true,
        onNeedRefresh() {
          // New version available — activate and reload immediately
          updateSW(true);
        },
        onRegisteredSW(_swUrl, registration) {
          // Poll for updates every 60s so new publishes are picked up fast
          if (registration) {
            setInterval(() => {
              registration.update().catch(() => {});
            }, 60 * 1000);
          }
        },
      });

      // Reload the page once the new SW takes control
      let refreshing = false;
      navigator.serviceWorker.addEventListener("controllerchange", () => {
        if (refreshing) return;
        refreshing = true;
        window.location.reload();
      });
    })
    .catch(() => {
      /* ignore */
    });
}

initOfflineSync();

createRoot(document.getElementById("root")!).render(<App />);
