// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-tasks.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's tasks. Optionally filter by completion status.",
  inputSchema: {
    completed: z.boolean().optional().describe("Filter by completion status."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ completed, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("tasks").select("id,title,description,priority,due_date,start_at,end_at,completed,created_at").order("created_at", { ascending: false }).limit(limit);
    if (typeof completed === "boolean") q = q.eq("completed", completed);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { tasks: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a new task for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Task title."),
    description: z2.string().optional(),
    priority: z2.enum(["none", "low", "medium", "high"]).default("none"),
    due_date: z2.string().optional().describe("ISO date (YYYY-MM-DD) or full ISO timestamp."),
    start_at: z2.string().optional().describe("ISO 8601 start timestamp."),
    end_at: z2.string().optional().describe("ISO 8601 end timestamp.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("tasks").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      description: input.description ?? null,
      priority: input.priority,
      due_date: input.due_date ?? null,
      start_at: input.start_at ?? null,
      end_at: input.end_at ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created task ${data.id}` }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as completed (or uncompleted).",
  inputSchema: {
    id: z3.string().uuid().describe("Task id."),
    completed: z3.boolean().default(true)
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, completed }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("tasks").update({ completed, completed_at: completed ? (/* @__PURE__ */ new Date()).toISOString() : null }).eq("id", id).eq("user_id", ctx.getUserId()).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Task ${id} \u2192 completed=${completed}` }], structuredContent: { task: data } };
  }
});

// src/lib/mcp/tools/list-notes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_notes_default = defineTool4({
  name: "list_notes",
  title: "List notes",
  description: "List the signed-in user's notes. Optional keyword search on title.",
  inputSchema: {
    query: z4.string().optional().describe("Case-insensitive substring match on title."),
    limit: z4.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb4(ctx).from("notes").select("id,title,content,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (query) q = q.ilike("title", `%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { notes: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-note.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_note_default = defineTool5({
  name: "create_note",
  title: "Create note",
  description: "Create a new Markdown note for the signed-in user.",
  inputSchema: {
    title: z5.string().trim().min(1),
    content: z5.string().default("").describe("Markdown body.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb5(ctx).from("notes").insert({
      user_id: ctx.getUserId(),
      title,
      content
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created note ${data.id}` }], structuredContent: { note: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aeyhgdlacoqsabsbrzia";
var mcp_default = defineMcp({
  name: "arshnaz-mcp",
  title: "ARSHNAZ",
  version: "0.1.0",
  instructions: "Access the signed-in user's ARSHNAZ tasks and notes. Use list_tasks / list_notes to read, create_task / create_note to add items, and complete_task to mark tasks done.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tasks_default, create_task_default, complete_task_default, list_notes_default, create_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
